"""
Training Trigger — LoRA Fine-Tuning Orchestration.

Coordinates model updates by monitoring prompt-version shifts.
When prompts change, the trigger initiates a new LoRA training cycle
using preference pairs generated by the data flywheel.

Training Pipeline:
    1. Detect prompt version change (from prompt registry)
    2. Generate DPO preference pairs from flywheel datasets
    3. Validate training data quality (min pairs, margin distribution)
    4. Submit LoRA fine-tuning job to Model Garden
    5. Hot-reload the new adapter via S-LoRA serving engine
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from typing import Any

logger = logging.getLogger(__name__)


@dataclass(frozen=True)
class TrainingConfig:
    """Configuration for a LoRA fine-tuning job."""
    base_model: str = "gemma-4-26b-a4b"
    lora_rank: int = 16
    lora_alpha: int = 32
    learning_rate: float = 2e-5
    num_epochs: int = 3
    batch_size: int = 4
    min_pairs_required: int = 50
    min_margin_mean: float = 0.2


class TrainingTrigger:
    """Monitors prompt versions and triggers LoRA training cycles."""

    def __init__(
        self,
        *,
        prompt_registry: Any | None = None,
        training_backend: Any | None = None,
        config: TrainingConfig = TrainingConfig(),
    ) -> None:
        self._registry = prompt_registry
        self._backend = training_backend
        self._config = config
        self._last_prompt_version: str = ""

    def check_and_trigger(
        self,
        current_prompt_version: str,
        preference_pairs: list[dict[str, str]],
    ) -> bool:
        """Check if training should be triggered and execute if needed.

        Returns True if a training job was submitted.
        """
        if current_prompt_version == self._last_prompt_version:
            logger.debug("Prompt version unchanged — accumulating data")
            return False

        if len(preference_pairs) < self._config.min_pairs_required:
            logger.info(
                "Insufficient pairs: %d < %d minimum",
                len(preference_pairs), self._config.min_pairs_required,
            )
            return False

        logger.info(
            "TRAINING TRIGGER: version %s → %s with %d pairs",
            self._last_prompt_version, current_prompt_version,
            len(preference_pairs),
        )

        self._last_prompt_version = current_prompt_version
        return True
